### ISSUE TITLE
Unknown type loff_t using gcc 8.2.1

### ISSUE THREAD

**Issue by krumelmonster** [doug16rogers/find-pwned-password#1]
When compiling using `make`, building find-pwned.c fails because `loff_t` is undefined using `gcc (GCC) 8.2.1 20181127` **Edit: glibc 2.28-5**
Using `-D_GNU_SOURCE` will fix the issue. Changing it to off_t seems to work as well.

    gcc -o find-pwned.o -Wall -Werror -std=c99 -c find-pwned.c
    find-pwned.c: In function ‘main’:
    find-pwned.c:676:5: error: unknown type name ‘loff_t’; did you mean ‘off_t’?
         loff_t file_size =  lseek(fd, 0, SEEK_END);
         ^~~~~~
         off_t
    make: *** [Makefile:7: find-pwned.o] Error 1`

**Comment by doug16rogers** [comment]
Sorry for the delay. This got lost in the noise of my inbox.

I used loff_t to ensure that it was 64-bit. The problem with off_t is that it is valid for it to be 32-bit. I didn't write it all down at the time but I know I was originally using _llseek(). Of course that's only good on Linux. When I switched back to lseek() I kept the type on file_size.

So... I'll take your suggestion. Thanks!
